### ISSUE TITLE
Add newsletter to the list

### ISSUE THREAD

**Issue by pogla** [alternbits/awesome-ai-newsletters#1]
@alternbit @dariubs Can you please add our [Mindstream newsletter](https://mindstream.news/) to your awesome AI newsletters list?

**Comment by dariubs** [comment]
of course, but can you please send a pull request here? i will merge

**Comment by pogla** [comment]
@dariubs Done!

https://github.com/alternbits/awesome-ai-newsletters/pull/2

**Comment by dariubs** [comment]
merged
